//Admin
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

//Auth
export const ADD_PROFILE = "ADD_PROFILE";
export const IS_USER_ADMIN_FAIL = "IS_USER_ADMIN_FAIL";
export const IS_USER_ADMIN_SUCCESS = "IS_USER_ADMIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const USER_EMAIL_CHANGE = "USER_EMAIL_CHANGE";
export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT";
export const USER_PASSWORD_CHANGE = "USER_PASSWORD_CHANGE";

//Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_EMAIL_ERRORS = "CLEAR_EMAIL_ERRORS";
export const CLEAR_PASSWORD_ERRORS = "CLEAR_PASSWORD_ERRORS";
export const EMAIL_VALIDATION_FAIL = "EMAIL_VALIDATION_FAIL";
export const EMAIL_VALIDATION_SUCCESS = "EMAIL_VALIDATION_SUCCESS";
export const PASSWORD_VALIDATION_FAIL = "PASSWORD_VALIDATION_FAIL";
export const PASSWORD_VALIDATION_SUCCESS = "PASSWORD_VALIDATION_SUCCESS";
export const UPDATE_RENDERS = "UPDATE_RENDERS";

// Generic
export const DO_NOTHING = "DO_NOTHING";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
